### ISSUE TITLE
Remove id from db.json file

### ISSUE THREAD

**Issue by volkanto** [alpercun/fancy-macbook-app#16]
I am not sure that where `id` field from `db.json` was used in the application but is that possible to get rid of using that field? Looks like it is making noise and creating lots of conflicts between pull requests when one of them is merged. Basically, wondering if `id` field is really used, if not I am going to remove it and raise a PR. Otherwise my suggestion is generate `id` dynamically in the code.

**Comment by alpercun** [comment]
I agree with your suggestion. Updating the id through the db creates a lot of trouble when new issues and PRs come in. I will take care of him. Thank you for your feedback. ⚡

**Comment by volkanto** [comment]
You can use the solution below if you want, I couldn't raise PR as I don't have any experience with Reach, didn't want to break anything :) 

```javascript
import db from '../../assets/db.json';

generateId(db);

function generateId(json) {
    json.forEach((item, index) => {
        item.id = ++index;
    });
    return json;
}
```
