### ISSUE TITLE
Display app suggester at the app card

### ISSUE THREAD

**Issue by hasantezcan** [alpercun/fancy-macbook-app#2]
We can display the app suggester on the app card like that. 👇

With this implementation, we can encourage people to suggest apps and we can increase the number of suggesters and apps.

> Example image: 
>
> <img width="373" alt="image" src="https://user-images.githubusercontent.com/32804505/215352583-9bf259b6-ad02-42cb-b7a5-c57bef33fd7b.png">

**Comment by alpercun** [comment]
We can add suggested by to look like this design.
<img width="459" alt="Screenshot 2023-02-06 at 22 02 28" src="https://user-images.githubusercontent.com/32914083/217061448-369bde7a-5e18-4743-9b2a-35e77c45b622.png">

**Comment by alpercun** [comment]
closes #25
