### ISSUE TITLE
[AddApp]: PDF Search

### ISSUE THREAD

**Issue by muharremozkan** [alpercun/fancy-macbook-app#23]
The content of the application to be added

```json
{
 "name": "pdf search",
 "logo": "https://pdfsearch.app/icon400.png",
 "description": "Search the contents of large numbers of documents using artificial intelligence.",
 "categories": ["Productivity", "Search"]
}
```

**Comment by volkanto** [comment]
Looks like `pdf search` is not part of brew cask. Either you can close the ticket or if possible please fix the app name which fits into brew cask application name.

**Comment by volkanto** [comment]
@alpercun let's close the issue.
